name: Wheat-api-deploy

on:
  push:
    branches: [ master ]

jobs:
  raspberrypi-test:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v2

      - name: folder remove content
        run: |
          sudo rm -rf ~/wheat-api/*

      - name: Move file
        run: |
          sudo su
          cp -R ~/actions-runner-api/_work/wheat-api/wheat-api  ~/
          cd ~/wheat-api && ls -al
      
      - name: Start Service Docker
        run: |
          sudo su
          cd ~/wheat-api && sudo make dev-setup
      
      - name: Start Service Docker
        run: |
          sudo su
          cd ~/wheat-api && sudo make dev-run
          rm -rf ~/actions-runner-api/_work