name: Wheat-api-deploy

on:
  push:
    branches: [ master ]

jobs:
  raspberrypi-test:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v2

      - name: folder remove content
        run: |
          sudo rm -rf ~/wheat-api
          mkdir ~/wheat-api

      - name: docker clean task
        run: |
          sudo make dev-stop

      - name: Move file
        run: |
          cp -R ~/actions-runner-api/_work/wheat-api/wheat-api  ~/
          cd ~/wheat-api
      
      - name: build  Docker Image
        run: |
          sudo su
          cd ~/wheat-api && sudo make dev-setup
      
      - name: Start Service Docker
        run: |
          sudo su
          cd ~/wheat-api && sudo make dev-run