name: Wheat-api-deploy

on:
  push:
    branches: [ master ]

jobs:
  raspberrypi-test:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v2

      - name: folder remove content
        run: |
          rm -rf ~/wheat-api/*

      - name: Move file
        run: |
          mv ./* ~/wheat-api
          ls -al